# .github/workflows/release.yaml

on:
  push: # 每次 push 的时候触发
  workflow_dispatch:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 这给予了 workflow 写入仓库内容的权限
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o PrivaCV_linux_amd64 cmd/server/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o PrivaCV_linux_arm64 cmd/server/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o PrivaCV_linux_arm cmd/server/main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build -o PrivaCV_linux_riscv64 cmd/server/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o PrivaCV_windows_amd64.exe cmd/server/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o PrivaCV_windows_arm64.exe cmd/server/main.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o PrivaCV_mac_amd64 cmd/server/main.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o PrivaCV_mac_arm64 cmd/server/main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动提供的 token
        with: # 将下述可执行文件 release 上去
          files: |
            PrivaCV_linux_amd64
            PrivaCV_linux_arm64
            PrivaCV_linux_arm
            PrivaCV_linux_riscv64
            PrivaCV_windows_amd64.exe
            PrivaCV_windows_arm64.exe
            PrivaCV_mac_amd64
            PrivaCV_mac_arm64